### ISSUE TITLE
How to persist javascript Objects using Messi?

### ISSUE THREAD

**Issue by sajushela** [MessiJS/MessiJS#71]
I load a dynamic Javascript which has below details

var newJob = newJob || {};

(function(newJob){

```
newJob.firstName = "Saju";

newJob.getData = function(){
    return "My Data is ...";
}
```

})(newJob);

When Messi popup is up, the above mentioned JS gets executed and newJob object is stored. 

But the issue is after parsing this js file, newJob object is undefined... So i am forced to use window.newJob to persist my objects. Which i feel is not correct.

Any suggestions for this issue?

**Comment by kgust** [comment]
Did you get this figured out?  Without seeing the entire file I can't be certain, but it appears that your problem is one of scope. Define your scope, using var, at the highest level that you need it. Then in the inner scopes, just reference it (don't use var). Passing in the value is also a good practice.

I'm not seeing any problems with the code that you've shown me here, nor would MessiJS cause a your variable to become undefined.
